### ISSUE TITLE
Planning List Variable Constraint

### ISSUE THREAD

**Issue by keremtatlici** [optapy/optapy-quickstarts#14]
We are try to use [EmployeeSchedule](https://github.com/optapy/optapy-quickstarts/tree/stable/employee-scheduling)   algorithm for n-n shift-employee schedule. But the algorithm assigns only one employee per shift. For this case we find that we need to use  planning_variable_list decorator (as shown as in the [vehicle](https://github.com/optapy/optapy-quickstarts/tree/stable/vehicle-routing) algorihm) and with this decorator we update our domain class. But our constraints are not working after we do this updates and we couldn't find any example to use constraints like situation that we are in.

If you may tell us that in the [EmployeeSchedule](https://github.com/optapy/optapy-quickstarts/tree/stable/employee-scheduling) how to do that we can manage to make it in our project

**Comment by Christopher-Chianelli** [comment]
I expect `@planning_list_variable` will not do what you expect; `@planning_list_variable` is primarily used to replace chained models, and corresponding have these properties:

- No item is shared between two list (ex: no location is visited twice by different vehicles)
- Every item is in at least one list (ex: every location is visited by a vehicle)
- The order in the list is significant (ex: visiting location A then location B is different from visiting location B then A).

Is the number of Employees per Shift known in advance? If so, you can solve this issue by creating N different Shift instances if a shift requires N employees.
