### ISSUE TITLE
Are these 3 lines needed?

### ISSUE THREAD

**Issue by ramdasrrao** [optapy/optapy-quickstarts#30]
https://github.com/optapy/optapy-quickstarts/blame/0ef8cf5790d13f167dead5ce036e134832b62d32/school-timetabling/domain.py#L193

Not sure the variable "lesson" is used anywhere. Is there a reason for these 3 lines? Just wondering as a newbie on quickstarts. Apologies if I couldn't figure it out.

**Comment by Christopher-Chianelli** [comment]
No, the lines are not needed. In this case, the lines are used to demonstrate you can pass an partially initialized problem to `optapy` (i.e. that `lesson` will have its timeslot and room set before being solved).

**Comment by ramdasrrao** [comment]
Thanks for the clarification. Really appreciate it. Perhaps, a comment will help.
